# Generated by Django 4.0.4 on 2022-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='serie'),
        ),
    ]
