# Generated by Django 4.0.4 on 2022-06-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
