# Generated by Django 4.0.4 on 2022-06-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_documental_serie_delete_genero_delete_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documental',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
